### ISSUE TITLE
KeyError: 28

### ISSUE THREAD

**Issue by Ezhug** [vanhbakaa/Coub#1]
Total followers: 0 followers
                Recoubs count: 0 recoubs
                Likes count: 0 likes
                Views count: 0 views

Traceback (most recent call last):
  File "D:\clicker\Coub\bot\core\tapper.py", line 597, in run
    self.get_user_rewards(session)
  File "D:\clicker\Coub\bot\core\tapper.py", line 322, in get_user_rewards
    if tasks[taskid['id']]['repeatable'] is True:
       ~~~~~^^^^^^^^^^^^^^
KeyError: 28
2024-10-12 17:29:00 | ERROR    | 620 - user121 | Unknown error: 28

**Comment by vanhbakaa** [comment]
How did you get that error bro lol

**Comment by vanhbakaa** [comment]
Fixed
