### ISSUE TITLE
KeyError: 20

### ISSUE THREAD

**Issue by sentient-ai69** [vanhbakaa/Coub#3]
I get error:

===test===
                Total followers: 0 followers
                Recoubs count: 0 recoubs
                Likes count: 51 likes
                Views count: 0 views
            
Traceback (most recent call last):
  File "/home/ubuntu/Coub/bot/core/tapper.py", line 478, in run
    self.get_user_rewards(session)
  File "/home/ubuntu/Coub/bot/core/tapper.py", line 301, in get_user_rewards
    if tasks[taskid['id']]['repeatable'] is True:
KeyError: 20
2024-10-13 04:41:45 | ERROR    | 502 - test | Unknown error: 20

**Comment by vanhbakaa** [comment]
Fixed
