### ISSUE TITLE
KeyError: 27

### ISSUE THREAD

**Issue by TrollGG174** [vanhbakaa/Coub#4]
Traceback (most recent call last):
  File "D:\teleBots\Coub-main\bot\core\tapper.py", line 489, in run
    await self.complete_not_repeat_tasks(session)
  File "D:\teleBots\Coub-main\bot\core\tapper.py", line 404, in complete_not_repeat_tasks
    self.get_lastest_user_rewards(session)
  File "D:\teleBots\Coub-main\bot\core\tapper.py", line 336, in get_lastest_user_rewards
    if tasks[taskid['id']]['repeatable'] is True:
       ~~~~~^^^^^^^^^^^^^^
KeyError: 27

**Comment by vanhbakaa** [comment]
Update the bot bro
