### ISSUE TITLE
KeyError: 24

### ISSUE THREAD

**Issue by 0xTaaa** [vanhbakaa/Coub#6]
Traceback (most recent call last):
File "/root/coubp/bot/core/tapper.py", line 490, in run
  await self.complete_repeat_tasks(session)
File "/root/coubp/bot/core/tapper.py", line 425, in complete_repeat_tasks
  self.get_lastest_user_rewards(session)
File "/root/coubp/bot/core/tapper.py", line 336, in get_lastest_user_rewards
if tasks[taskid['id']]['repeatable'] is True:
KeyError: 24

**Comment by vanhbakaa** [comment]
Fixed
