### ISSUE TITLE
OSError: Connection lost

### ISSUE THREAD

**Issue by tnttol** [vanhbakaa/Coub#7]
socket.send() raised exception.
Task exception was never retrieved
future: <Task finished name='Task-41' coro=<Client.handle_updates() done, defined at /home/name/.local/lib/python3.11/site-packages/pyrogram/client.py:535> exception=OSError(ConnectionResetError('Connection lost'))>
Traceback (most recent call last):
  File "/home/name/.local/lib/python3.11/site-packages/pyrogram/client.py", line 589, in handle_updates
    diff = await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/pyrogram/session/session.py", line 412, in invoke
    return await self.invoke(query, retries - 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 7 more times]
  File "/home/name/.local/lib/python3.11/site-packages/pyrogram/session/session.py", line 402, in invoke
    raise e from None
  File "/home/name/.local/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/name/.local/lib/python3.11/site-packages/pyrogram/session/session.py", line 340, in send
    raise e
  File "/home/name/.local/lib/python3.11/site-packages/pyrogram/session/session.py", line 337, in send
    await self.connection.send(payload)
  File "/home/name/.local/lib/python3.11/site-packages/pyrogram/connection/connection.py", line 69, in send
    await self.protocol.send(data)
  File "/home/name/.local/lib/python3.11/site-packages/pyrogram/connection/transport/tcp/tcp_abridged.py", line 38, in send
    await super().send(
  File "/home/name/.local/lib/python3.11/site-packages/pyrogram/connection/transport/tcp/tcp.py", line 104, in send
    raise OSError(e)
OSError: Connection lost

**Comment by vanhbakaa** [comment]
Check your internet connection then run again
